// GENERATED by scripts/stamp-build.sh — do not edit. Rendered in the corner at all times so that
// any bug report identifies what was actually running. A trailing "+" on the SHA means the tree was
// dirty at stamp time, i.e. this build matches no commit.
window.BUILD = { sha: "9d52857", v: "lt-v6", at: "2026-09-03T15:44Z" };
