// GENERATED by scripts/stamp-build.sh — do not edit. Rendered in the corner at all times so that
// any bug report identifies what was actually running. A trailing "+" on the SHA means the tree was
// dirty at stamp time, i.e. this build matches no commit.
window.BUILD = { sha: "38a964a", v: "lt-v11", at: "2026-09-04T02:04Z" };
