#!/usr/bin/env node
// Generates assets/icon.svg from the SAME formula the app plots, so the brand mark and the running
// figure can never drift apart. Per ADDENDUM section 4 the 2:1 phasor ratio traces a FIXED limacon
// — shape reads as timbre, motion reads as error — so the mark shows a limacon WITH A TRAIL: the
// taper and the bright head are what carry "this thing rotates". A bare closed curve reads as a
// piece of fruit, which is how the first attempt went.
//
//   x = cos t + w cos(2t + phi)      y = sin t + w sin(2t + phi)
//
// Usage: node scripts/make-figure.mjs [variant]        (default: ship)
//        FIGURE_OUT=/tmp/x.svg node scripts/make-figure.mjs open
import { writeFileSync } from "node:fs";

const W = 0.4;            // overtone mix weight — the app's VIZ default
const SEGS = 240;         // trail segments; enough that the taper looks continuous at 512px

function pts(w, phi, n) {
  const a = [];
  for (let k = 0; k <= n; k++) {
    const t = (k / n) * 2 * Math.PI;
    a.push([Math.cos(t) + w * Math.cos(2 * t + phi), Math.sin(t) + w * Math.sin(2 * t + phi)]);
  }
  return a;
}

// Fit to radius R about (cx,cy); y flipped for SVG's downward axis.
function fit(a, cx, cy, R) {
  let m = 0;
  for (const [x, y] of a) m = Math.max(m, Math.hypot(x, y));
  return a.map(([x, y]) => [cx + (x * R) / m, cy - (y * R) / m]);
}

// A tapered trail: one <path> per segment, opacity + width ramping toward the head. Cheap, and it
// survives rasterization at 32px far better than a stroke gradient (which greys to mush).
function trail(p, { stroke, wMax, wMin, oMax, oMin }) {
  const out = [];
  for (let i = 1; i < p.length; i++) {
    const f = i / (p.length - 1);                    // 0 = tail, 1 = head
    const o = (oMin + (oMax - oMin) * f).toFixed(3);
    const w = (wMin + (wMax - wMin) * f).toFixed(1);
    out.push(`<path d="M${p[i-1][0].toFixed(1)},${p[i-1][1].toFixed(1)}L${p[i][0].toFixed(1)},${p[i][1].toFixed(1)}" `
           + `stroke="${stroke}" stroke-width="${w}" stroke-linecap="round" opacity="${o}"/>`);
  }
  return out.join("\n    ");
}

const VARIANTS = {
  ship: { phi: 0,           cut: 1.0,  head: true },   // dimple left, closed trail
  up:   { phi: Math.PI / 2, cut: 1.0,  head: true },   // dimple up — reads as fruit; kept for comparison
  open: { phi: 0,           cut: 0.88, head: true },   // stops short of closing; the gap says "still moving"
};

const name = process.argv[2] || "ship";
const v = VARIANTS[name];
if (!v) { console.error(`unknown variant ${name}; try: ${Object.keys(VARIANTS).join(", ")}`); process.exit(1); }

const all = fit(pts(W, v.phi, SEGS), 256, 256, 170);
const p = all.slice(0, Math.max(2, Math.round(all.length * v.cut)));
const head = p[p.length - 1];

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- GENERATED by scripts/make-figure.mjs (variant: ${name}) — do not hand-edit; regenerate, then
       run scripts/make-icons.sh. The curve is exactly what the app plots: the f0 phasor composited
       with the ${W}-weighted 2*f0 phasor. A limacon (ADDENDUM section 4), drawn with a decay trail
       because motion, not shape, is what the figure means. -->
  <defs>
    <radialGradient id="glow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#2ee6a8" stop-opacity=".22"/>
      <stop offset="100%" stop-color="#2ee6a8" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="512" height="512" rx="112" fill="#0e1413"/>
  <circle cx="256" cy="256" r="205" fill="url(#glow)"/>
  <g fill="none">
    ${trail(p, { stroke: "#2ee6a8", wMax: 40, wMin: 9, oMax: 1, oMin: 0.13 })}
  </g>${v.head ? `
  <circle cx="${head[0].toFixed(1)}" cy="${head[1].toFixed(1)}" r="27" fill="#eafff7"/>` : ""}
</svg>
`;

const out = process.env.FIGURE_OUT || "assets/icon.svg";
writeFileSync(out, svg);
console.log(`wrote ${out} (variant: ${name}, ${svg.length} bytes)`);

// ---- share card ------------------------------------------------------------
// Same curve, same generator, so the card and the icon cannot drift. Fonts are named EXPLICITLY
// (Georgia / Helvetica, both present on macOS) rather than system-ui: rsvg-convert resolves through
// fontconfig, where "system-ui" is not a real family and silently falls back to a stock serif.
if (!process.env.FIGURE_OUT) {
  const c = fit(pts(W, 0, SEGS), 950, 315, 186);
  const chead = c[c.length - 1];
  const og = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630">
  <!-- GENERATED by scripts/make-figure.mjs — do not hand-edit; regenerate, then run
       scripts/make-og.sh (which rasterizes AND enforces the <250 KB scrape budget). -->
  <defs>
    <radialGradient id="g" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#2ee6a8" stop-opacity=".20"/>
      <stop offset="100%" stop-color="#2ee6a8" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="#0e1413"/>
  <circle cx="950" cy="315" r="250" fill="url(#g)"/>
  <g fill="none">
    ${trail(c, { stroke: "#2ee6a8", wMax: 30, wMin: 6, oMax: 1, oMin: 0.12 })}
  </g>
  <circle cx="${chead[0].toFixed(1)}" cy="${chead[1].toFixed(1)}" r="20" fill="#eafff7"/>
  <text x="90" y="286" font-family="Georgia, serif" font-size="82" font-weight="700" fill="#e8efed">Lissajous Tuner</text>
  <text x="92" y="348" font-family="Helvetica, Arial, sans-serif" font-size="32" fill="#8b9a97">Phase-coherent tuning for violin, viola and cello.</text>
  <text x="92" y="396" font-family="Helvetica, Arial, sans-serif" font-size="32" fill="#8b9a97">Tuning error is rotation, not a needle.</text>
</svg>
`;
  writeFileSync("assets/og.svg", og);
  console.log(`wrote assets/og.svg (${og.length} bytes)`);
}
