#!/usr/bin/env bash
# Regenerate build.js — the always-visible build id.
#
# Whatever is on screen must be identifiable from a photo or a one-line bug report, so this stamps
# the short git SHA and the service-worker cache generation into a file the app renders in the
# corner AT ALL TIMES, not just under ?dev=1. If a report says "it jitters" the first question is
# always "which build?", and this is what stops that costing a round trip.
#
# build.js is in sw.js's SHELL, so it changes on every deploy and V must be bumped with it — which
# is exactly the discipline scripts/sw-lint.py enforces. scripts/deploy.sh does both.
set -euo pipefail
cd "$(dirname "$0")/.."

sha="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
# A dirty tree is a build that does not correspond to any commit. Say so, loudly, in the id itself:
# testing uncommitted code and reporting it as the committed SHA is its own lost cycle.
if ! git diff --quiet HEAD -- . ':(exclude)build.js' 2>/dev/null; then sha="${sha}+"; fi
v="$(grep -o 'const V = "[^"]*"' sw.js | head -1 | sed 's/.*"\(.*\)"/\1/')"

cat > build.js <<EOF
// GENERATED by scripts/stamp-build.sh — do not edit. Rendered in the corner at all times so that
// any bug report identifies what was actually running. A trailing "+" on the SHA means the tree was
// dirty at stamp time, i.e. this build matches no commit.
window.BUILD = { sha: "${sha}", v: "${v}", at: "$(date -u +%Y-%m-%dT%H:%MZ)" };
EOF
echo "build.js: ${sha} / ${v}"
